spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    defer-datasource-initialization: true
    show-sql: true
  main:
    banner-mode: off
  logging:
    level:
      org:
        springframework:
          security: debug
      sql: debug
  profiles:
    active: prod
  server:
    port: 8080
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  accessSecretKey: "716f6f496e21776646527c5d7e2d4d4c205b382f6c392c267e512e2349"
  refreshSecretKey: "716f6f496e21776646527c5d7e2d999c205b382f6c392c267e512e2349"
  access-token-expiration-time: 15
  refresh-token-expiration-time: 10
cloudinary:
  cloudName: "drbxd4tkj"
  apiKey: "621377172471399"
  apiSecret: "2WSu2bvSVzuUFqiE508LLXq5DuQ"




