spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    defer-datasource-initialization: true
    show-sql: true
  main:
    banner-mode: off
  logging:
    level:
      org:
        springframework:
          security: debug
      sql: debug
  profiles:
    active: prod
  server:
    port: 8080
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  accessSecretKey: ${ACCESS_KEY}
  refreshSecretKey: ${REFRESH_KEY}
  access-token-expiration-time: 15
  refresh-token-expiration-time: 10
cloudinary:
  cloudName: ${CLOUD_NAME}
  apiKey: ${API_KEY}
  apiSecret: ${API_SECRET}





